# Generated by Django 6.0.5 on 2026-05-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TNAFHQResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200)),
                ('employee_code', models.CharField(max_length=100)),
                ('role', models.CharField(default='FH', max_length=10)),
                ('function', models.CharField(choices=[('sales_marketing', 'Sales & Marketing'), ('engineering', 'Engineering'), ('new_product_dev', 'New Product Development'), ('finance', 'Finance'), ('hr', 'Human Resources'), ('procurement', 'Procurement & Localisation'), ('scm_logistics', 'SCM & Logistics'), ('it_digital', 'IT & Digital'), ('manufacturing', 'Manufacturing')], max_length=50)),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('competency_ratings', models.JSONField(default=dict)),
                ('q_critical', models.TextField(blank=True)),
                ('q_gap_risk', models.TextField(blank=True)),
                ('q_ojt', models.TextField(blank=True)),
                ('q_alp', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'FHQ Response',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TNASelfAssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200)),
                ('employee_code', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('FH', 'Functional Head / Manager / GM'), ('GET', 'Graduate Engineer Trainee (GET)'), ('MT', 'Management Trainee (MT)')], max_length=10)),
                ('function', models.CharField(choices=[('sales_marketing', 'Sales & Marketing'), ('engineering', 'Engineering'), ('new_product_dev', 'New Product Development'), ('finance', 'Finance'), ('hr', 'Human Resources'), ('procurement', 'Procurement & Localisation'), ('scm_logistics', 'SCM & Logistics'), ('it_digital', 'IT & Digital'), ('manufacturing', 'Manufacturing')], max_length=50)),
                ('date', models.DateField()),
                ('competency_ratings', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Self-Assessment Response',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
