"""
JSW Motors — Competency TNA Portal
KPI-aligned competency framework for all 9 functions.
Source: JSW Motors Functional Scorecard FY2026–FY2030
"""

PROFICIENCY_SCALE = [
    {'level': 1, 'label': 'Awareness',    'desc': 'Theoretical knowledge only; cannot apply independently'},
    {'level': 2, 'label': 'Basic',        'desc': 'Can perform with supervision and guidance'},
    {'level': 3, 'label': 'Practitioner', 'desc': 'Performs independently and consistently'},
    {'level': 4, 'label': 'Advanced',     'desc': 'Coaches others; handles complex situations'},
    {'level': 5, 'label': 'Expert',       'desc': 'Sets standards; innovates; recognised domain authority'},
]

IMPORTANCE_SCALE = [
    {'level': 1, 'label': 'Low'},
    {'level': 2, 'label': 'Moderate'},
    {'level': 3, 'label': 'Important'},
    {'level': 4, 'label': 'High'},
    {'level': 5, 'label': 'Critical'},
]

FHQ_OPEN_QUESTIONS = [
    {'key': 'q_critical',  'text': 'Which single competency is most critical for a trainee entering your function within the first 30 days? Why?'},
    {'key': 'q_gap_risk',  'text': 'What is the biggest competency gap risk you foresee from campus-hired GET/MT trainees in your function?'},
    {'key': 'q_ojt',       'text': 'What on-the-job learning experience best builds the core competency for your function? (e.g. rotation, project, shadowing)'},
    {'key': 'q_alp',       'text': 'Suggest a theme or problem statement for the 2-month Action Learning Project (ALP) for trainees in your function.'},
]

FUNCTIONS = {
    'sales_marketing': {
        'label': 'Sales & Marketing',
        'short': 'S&M',
        'icon': '📈',
        'head_title': 'Chief Sales Officer / VP Sales & Marketing',
        'comps': [
            {'code': 'SM01', 'category': 'Technical', 'ev_critical': False,
             'name': 'Sales Strategy & Go-to-Market Planning',
             'kpi_link': 'Retail Sales Volume, Wholesale Dispatch, Revenue vs Plan %',
             'description': 'Designing territory sales plans, setting KPIs, identifying market segments and developing GTM strategies for EV products across dealer and digital channels.'},
            {'code': 'SM02', 'category': 'Technical', 'ev_critical': True,
             'name': 'EV Market Intelligence & Competitive Landscape',
             'kpi_link': 'Market Share (NEV Segment), Brand Awareness Score, EV Adoption Campaign Reach',
             'description': 'India EV market trends, FAME/PLI policy awareness, competitor product benchmarking and understanding customer EV adoption barriers.'},
            {'code': 'SM03', 'category': 'Technical', 'ev_critical': False,
             'name': 'CRM Analytics & Sales Pipeline Management',
             'kpi_link': 'Lead Response Time, Retail-to-Booking Conversion %, Digital Lead Share %',
             'description': 'CRM platform proficiency, pipeline analytics, win-loss analysis, lead qualification, conversion optimisation and reporting dashboards.'},
            {'code': 'SM04', 'category': 'Technical', 'ev_critical': False,
             'name': 'Digital Marketing & Performance Marketing',
             'kpi_link': 'Digital Lead Share %, Cost per Lead (₹), Marketing ROI',
             'description': 'Planning and managing digital campaigns, performance marketing, SEO/SEM strategy, social media calendar and analytics-driven marketing decisions.'},
            {'code': 'SM05', 'category': 'Technical', 'ev_critical': False,
             'name': 'Channel & Dealer Network Development',
             'kpi_link': 'Dealer Network Expansion (Count), Dealer Satisfaction Index (DSI)',
             'description': 'Automotive dealer network management, dealer financial viability assessment, appointment process, performance dashboards and dealer development.'},
            {'code': 'SM06', 'category': 'Technical', 'ev_critical': False,
             'name': 'Revenue & P&L Management',
             'kpi_link': 'Average Realisation per Unit, Revenue vs Plan %, Cost per Lead',
             'description': 'P&L structure for the sales function, revenue recognition, contribution margin calculation, break-even analysis and financial impact of sales decisions.'},
            {'code': 'SM07', 'category': 'Technical', 'ev_critical': False,
             'name': 'Customer Experience & NPS Management',
             'kpi_link': 'Customer Satisfaction (CSAT/NPS), Retail-to-Booking Conversion %',
             'description': 'Building and sustaining customer relationships, managing objections, monitoring NPS, and driving post-purchase engagement for long-term satisfaction.'},
            {'code': 'SM08', 'category': 'Technical', 'ev_critical': False,
             'name': 'Brand Strategy & EV Positioning',
             'kpi_link': 'Brand Awareness Score, EV Adoption Campaign Reach',
             'description': 'Brand architecture, EV brand building, brand positioning strategy, equity measurement and aligning marketing communications to JSW Motors brand identity.'},
            {'code': 'SM09', 'category': 'Technical', 'ev_critical': False,
             'name': 'After-Sales & Service Market Development',
             'kpi_link': 'Service Market Penetration %, Warranty Cost per Vehicle (₹)',
             'description': 'Growing vehicle service penetration at authorised networks, managing warranty cost drivers, and building after-sales revenue streams.'},
            {'code': 'SM10', 'category': 'Technical', 'ev_critical': False,
             'name': 'Sales Forecasting & Analytics',
             'kpi_link': 'Wholesale Dispatch Volume, Revenue vs Plan %, Digital Lead Share %',
             'description': 'Territory-wise analysis, conversion metrics, monthly forecasts, variance commentary for MIS reviews and data-driven territory management.'},
            {'code': 'SM11', 'category': 'Behavioral', 'ev_critical': False,
             'name': 'Negotiation & Commercial Influence',
             'kpi_link': 'Average Realisation per Unit, Dealer Satisfaction Index',
             'description': 'Negotiating channel agreements and customer deals, managing stakeholder trade-offs and influencing commercial decisions without direct authority.'},
            {'code': 'SM12', 'category': 'Behavioral', 'ev_critical': False,
             'name': 'Cross-Functional Collaboration',
             'kpi_link': 'Revenue vs Plan %, Service Market Penetration %',
             'description': 'Working effectively with Product, Finance, SCM, Engineering and After-Sales teams for seamless sales execution and customer delivery.'},
            {'code': 'SM13', 'category': 'Behavioral', 'ev_critical': False,
             'name': 'Data-Driven Decision Making',
             'kpi_link': 'CRM Analytics, Marketing ROI, Cost per Lead, Conversion %',
             'description': 'Using market data, CRM analytics, financial metrics and competitive intelligence to drive pricing, territory and channel strategy decisions.'},
            {'code': 'SM14', 'category': 'Behavioral', 'ev_critical': False,
             'name': 'Communication & Executive Storytelling',
             'kpi_link': 'Dealer Satisfaction Index, Brand Awareness Score',
             'description': 'Clarity and confidence in written and verbal communications with customers, dealers and leadership; presenting data-driven sales stories.'},
            {'code': 'SM15', 'category': 'Behavioral', 'ev_critical': False,
             'name': 'Resilience, Agility & Growth Mindset',
             'kpi_link': 'Retail Sales Volume, Market Share (NEV Segment)',
             'description': 'Learning from losses, iterating sales approach, maintaining energy and adaptability in a fast-growing, highly competitive EV market.'},
        ],
    },

    'engineering': {
        'label': 'Engineering',
        'short': 'Engg',
        'icon': '⚙️',
        'head_title': 'Chief Engineering Officer / VP Engineering',
        'comps': [
            {'code': 'EN01', 'category': 'Technical', 'ev_critical': True,
             'name': 'EV Powertrain & Vehicle System Architecture',
             'kpi_link': 'Vehicle Range vs Target, 0-100 Performance vs Spec, NVH Index',
             'description': 'EV drivetrain components: traction motor, inverter, battery pack, BMS, charging system and e-axle; system integration for BEV/HEV/PHEV architectures.'},
            {'code': 'EN02', 'category': 'Technical', 'ev_critical': True,
             'name': 'Functional Safety (ISO 26262) & HV System Awareness',
             'kpi_link': 'Crash Test Rating, Field Defect Rate (Eng Origin), Homologation Clearance On-Time',
             'description': 'Functional safety requirements for EV, ASIL ratings, ISO 26262 linkage to product engineering, HV system safety design and crash test compliance.'},
            {'code': 'EN03', 'category': 'Technical', 'ev_critical': False,
             'name': 'Design Validation & DVP Management',
             'kpi_link': 'Engineering DVP Completion %, Design Freeze On-Schedule %',
             'description': 'Design Validation Plan development, managing test schedules, DVP completion tracking, and gate readiness review for product development milestones.'},
            {'code': 'EN04', 'category': 'Technical', 'ev_critical': False,
             'name': 'DFMEA / PFMEA & Quality Engineering',
             'kpi_link': 'DFMEA Coverage %, Field Defect Rate (Eng Origin) PPM',
             'description': 'Design and Process Failure Mode & Effects Analysis, RPN calculation, control plan linkage and managing engineering-origin defect rate at field.'},
            {'code': 'EN05', 'category': 'Technical', 'ev_critical': False,
             'name': 'Cost Engineering & BOM Value Management',
             'kpi_link': 'BOM Cost vs Target %, Value Engineering Savings (₹ Cr)',
             'description': 'Standard costing, should-cost analysis, VE/VA initiatives, gross margin by platform, and systematic BOM cost reduction without functionality compromise.'},
            {'code': 'EN06', 'category': 'Technical', 'ev_critical': True,
             'name': 'Software & Embedded Systems Engineering',
             'kpi_link': 'ECU / Software Release Defect Density (Defects/KLOC)',
             'description': 'Embedded software development lifecycle, ECU specification, software defect management, OTA architecture awareness and software release governance.'},
            {'code': 'EN07', 'category': 'Technical', 'ev_critical': False,
             'name': 'Homologation & Regulatory Compliance',
             'kpi_link': 'Homologation Clearance On-Time %, RoHS / Hazardous Material Compliance %',
             'description': 'Type approval, CMVR compliance, AIS standards, obtaining regulatory clearances before SOP and managing hazardous material compliance across the vehicle BOM.'},
            {'code': 'EN08', 'category': 'Technical', 'ev_critical': False,
             'name': 'CAD / CAE & Digital Engineering Tools',
             'kpi_link': 'Design Freeze On-Schedule %, DVP Completion %',
             'description': 'CATIA/SolidWorks/AutoCAD proficiency, GD&T, 3D modelling, tolerance stack-up and engineering drawing interpretation for product development.'},
            {'code': 'EN09', 'category': 'Technical', 'ev_critical': False,
             'name': 'Platform Engineering & Modular Architecture',
             'kpi_link': 'Platform Reuse Index %, CAPEX vs Approved Budget %',
             'description': 'Modular vehicle architecture design, component commonality strategy, design-for-reuse principles and reducing tooling investment across platforms.'},
            {'code': 'EN10', 'category': 'Technical', 'ev_critical': False,
             'name': 'CAPEX & Engineering Program Budget Management',
             'kpi_link': 'CAPEX vs Approved Budget %, Value Engineering Savings (₹ Cr)',
             'description': 'Tooling and validation CAPEX planning, budget monitoring, change request impact assessment and managing engineering spend within sanctioned budget.'},
            {'code': 'EN11', 'category': 'Behavioral', 'ev_critical': False,
             'name': 'Analytical & Structured Problem Solving',
             'kpi_link': 'Field Defect Rate PPM, DVP Completion %',
             'description': '8D, 5-Why, A3 problem-solving methodology applied to engineering failures, quality escapes and field defect root cause resolution.'},
            {'code': 'EN12', 'category': 'Behavioral', 'ev_critical': False,
             'name': 'Cross-Functional Collaboration (Mfg/Quality/Procurement)',
             'kpi_link': 'BOM Cost vs Target %, DFMEA Coverage %, Homologation On-Time',
             'description': 'Working effectively with Manufacturing, Quality, Procurement and SCM teams on DFM, PPAP support and platform launch readiness.'},
            {'code': 'EN13', 'category': 'Behavioral', 'ev_critical': False,
             'name': 'Sustainability & Green Engineering Mindset',
             'kpi_link': 'Recyclability Index per Platform %, RoHS / Hazardous Material Compliance %',
             'description': 'Designing for end-of-life recyclability, reducing hazardous materials, CO₂ reduction through engineering choices and meeting JSW Motors ESG targets.'},
            {'code': 'EN14', 'category': 'Behavioral', 'ev_critical': False,
             'name': 'Technical Communication & Engineering Reporting',
             'kpi_link': 'DVP Completion %, Design Freeze On-Time %',
             'description': 'Writing clear engineering reports, presenting process data and design decisions to leadership, managing technical communication across functions.'},
        ],
    },

    'new_product_dev': {
        'label': 'New Product Development',
        'short': 'NPD',
        'icon': '🚗',
        'head_title': 'Chief Product Officer / VP New Product Development',
        'comps': [
            {'code': 'NPD01', 'category': 'Technical', 'ev_critical': False,
             'name': 'Product Program Management & Stage-Gate Governance',
             'kpi_link': 'SOP Milestone Achievement %, Concept-to-SOP Cycle Time (months)',
             'description': 'End-to-end product program management from concept to SOP using stage-gate methodology, milestone tracking and executive reporting.'},
            {'code': 'NPD02', 'category': 'Technical', 'ev_critical': False,
             'name': 'Voice of Customer & Consumer Insights Integration',
             'kpi_link': 'VoC Integration Score %, Customer Satisfaction (NPS)',
             'description': 'Designing and executing VoC research, translating consumer insights into product features and ensuring customer themes are addressed in product concepts.'},
            {'code': 'NPD03', 'category': 'Technical', 'ev_critical': True,
             'name': 'Competitive Intelligence & Product Benchmarking',
             'kpi_link': 'Competitive Feature Parity Index %, Price-to-Value Positioning Score',
             'description': 'Systematic competitor product benchmarking, feature parity tracking across top EV competitors and maintaining price-value positioning advantage.'},
            {'code': 'NPD04', 'category': 'Technical', 'ev_critical': True,
             'name': 'EV Software Architecture & OTA Capability',
             'kpi_link': 'EV Software / OTA Capability Readiness %, ECU Defect Density',
             'description': 'Understanding software-defined vehicle architecture, OTA update platforms, telematics integration and connected vehicle feature roadmap management.'},
            {'code': 'NPD05', 'category': 'Technical', 'ev_critical': True,
             'name': 'ADAS & Emerging Technology Integration',
             'kpi_link': 'ADAS Feature Integration per Model (L1/L2/L2+)',
             'description': 'ADAS feature planning and validation (L1/L2/L2+), sensor fusion awareness, camera-radar-LiDAR integration concepts and future technology roadmapping.'},
            {'code': 'NPD06', 'category': 'Technical', 'ev_critical': False,
             'name': 'Localisation Strategy & SOP Readiness Management',
             'kpi_link': 'Localisation Level at SOP %, Supplier Base Development',
             'description': 'Local content planning from concept stage, coordinating with Procurement for domestic vendor development and managing localisation milestones to SOP.'},
            {'code': 'NPD07', 'category': 'Technical', 'ev_critical': False,
             'name': 'Program Budget & CAPEX Governance',
             'kpi_link': 'Program Budget Adherence %, CAPEX vs Approved Budget',
             'description': 'Program cost tracking, tooling CAPEX management, budget adherence monitoring and managing engineering change financial impact across programs.'},
            {'code': 'NPD08', 'category': 'Technical', 'ev_critical': False,
             'name': 'Risk Management & Engineering Change Control',
             'kpi_link': 'Risk Register Coverage %, Change Request Resolution TAT (days)',
             'description': 'Identifying and mitigating program risks, maintaining risk registers with mitigation plans, and managing vehicle-level ECR resolution within TAT.'},
            {'code': 'NPD09', 'category': 'Technical', 'ev_critical': False,
             'name': 'Prototype Build Management & Validation',
             'kpi_link': 'Prototype Build Schedule Adherence %, DVP Completion %',
             'description': 'Coordinating prototype builds, managing build schedules across teams, tracking validation progress and ensuring readiness for design freeze gates.'},
            {'code': 'NPD10', 'category': 'Technical', 'ev_critical': False,
             'name': 'Intellectual Property & Innovation Management',
             'kpi_link': 'IP Filed (Patents) — Count',
             'description': 'Identifying patentable innovations in product development, supporting patent filings, managing IP strategy and building a culture of innovation.'},
            {'code': 'NPD11', 'category': 'Behavioral', 'ev_critical': False,
             'name': 'Cross-Functional Leadership & Stakeholder Alignment',
             'kpi_link': 'SOP Milestone Achievement %, Program Budget Adherence',
             'description': 'Aligning Engineering, Procurement, Manufacturing and Sales on program requirements, managing cross-functional dependencies and resolving conflicts.'},
            {'code': 'NPD12', 'category': 'Behavioral', 'ev_critical': False,
             'name': 'Strategic Portfolio & Pipeline Management',
             'kpi_link': 'Number of Models in Active Pipeline, Concept-to-SOP Cycle Time',
             'description': 'Managing multiple programs in parallel, balancing portfolio priorities, resource allocation across programs and strategic decision-making on product pipeline.'},
            {'code': 'NPD13', 'category': 'Behavioral', 'ev_critical': False,
             'name': 'Data-Driven Product Decision Making',
             'kpi_link': 'Price-to-Value Positioning Score, VoC Integration Score, Competitive Parity Index',
             'description': 'Using market research, customer data, competitive benchmarks and financial metrics to make evidence-based product planning and feature prioritisation decisions.'},
            {'code': 'NPD14', 'category': 'Behavioral', 'ev_critical': False,
             'name': 'Executive Communication & Program Reporting',
             'kpi_link': 'SOP Milestone Achievement %, Risk Register Coverage',
             'description': 'Preparing and delivering board-level program updates, milestone review presentations, risk escalation communications and program narrative management.'},
        ],
    },

    'finance': {
        'label': 'Finance',
        'short': 'Fin',
        'icon': '💰',
        'head_title': 'CFO / VP Finance',
        'comps': [
            {'code': 'FIN01', 'category': 'Technical', 'ev_critical': False,
             'name': 'Financial Modelling & 3-Statement Analysis',
             'kpi_link': 'Revenue vs AOP %, EBITDA (₹ Cr), Gross Margin %',
             'description': 'Building dynamic 3-statement financial models (P&L, Balance Sheet, Cash Flow), DCF basics, scenario planning and forecasting in Excel/ERP.'},
            {'code': 'FIN02', 'category': 'Technical', 'ev_critical': False,
             'name': 'Management Accounting & Cost Controlling',
             'kpi_link': 'Gross Margin %, SGA as % of Revenue, Cost Reduction Savings (₹ Cr)',
             'description': 'Cost centre vs profit centre accounting, overhead allocation, variance analysis, product costing and cost reduction programme management.'},
            {'code': 'FIN03', 'category': 'Technical', 'ev_critical': False,
             'name': 'CAPEX Planning, Tracking & Governance',
             'kpi_link': 'CAPEX vs Budget (₹ Cr)',
             'description': 'CAPEX budgeting, actual vs sanctioned monitoring, capitalisation policies, project spend tracking and CAPEX governance for a greenfield OEM.'},
            {'code': 'FIN04', 'category': 'Technical', 'ev_critical': False,
             'name': 'Working Capital & Treasury Management',
             'kpi_link': 'Working Capital Days, Cash & Liquidity Cover (months), Inventory DSI',
             'description': 'Managing debtor, creditor and inventory cycles, cash flow forecasting, liquidity management, treasury investments and banking relationship management.'},
            {'code': 'FIN05', 'category': 'Technical', 'ev_critical': False,
             'name': 'Budgeting, Forecasting & Rolling Estimates',
             'kpi_link': 'Budget Variance Accuracy %, MIS & Board Reporting On-Time %',
             'description': 'Annual budget process, rolling forecast cycles, bridge analysis between actuals and budget, and preparing accurate quarterly estimate inputs.'},
            {'code': 'FIN06', 'category': 'Technical', 'ev_critical': False,
             'name': 'Financial Reporting & MIS (Ind AS)',
             'kpi_link': 'MIS & Board Reporting On-Time %, Revenue vs AOP %',
             'description': 'P&L, Balance Sheet, Cash Flow interpretation under Ind AS, ratio analysis, board pack preparation and investor-ready financial reporting.'},
            {'code': 'FIN07', 'category': 'Technical', 'ev_critical': False,
             'name': 'Statutory Compliance & Internal Audit Management',
             'kpi_link': 'Statutory Compliance — Zero Lapses, Internal Audit High-Risk Findings Closed %',
             'description': 'GST, TDS, corporate tax filings, FEMA compliance, managing statutory audits and ensuring internal audit high-risk findings are closed within 90 days.'},
            {'code': 'FIN08', 'category': 'Technical', 'ev_critical': False,
             'name': 'SAP FICO & ERP Finance Modules',
             'kpi_link': 'MIS & Board Reporting On-Time %, Statutory Compliance',
             'description': 'SAP FI/CO modules: GL posting, cost centre accounting, internal orders, financial reporting, AP/AR management and ERP-based financial controls.'},
            {'code': 'FIN09', 'category': 'Technical', 'ev_critical': False,
             'name': 'Fundraising, Debt Management & Investor Relations',
             'kpi_link': 'Fundraising / Debt Drawdown vs Plan %, Credit Rating Maintenance',
             'description': 'Debt fundraising processes, investor communication, credit rating management, covenant compliance and managing banking and investor relationships.'},
            {'code': 'FIN10', 'category': 'Behavioral', 'ev_critical': False,
             'name': 'Business Partnering & Commercial Advisory',
             'kpi_link': 'Revenue vs AOP %, Budget Variance, Cost Reduction',
             'description': 'Acting as a finance business partner to functional heads, translating financial data into business insights and supporting commercial decision-making.'},
            {'code': 'FIN11', 'category': 'Behavioral', 'ev_critical': False,
             'name': 'Analytical Thinking & Financial Insights',
             'kpi_link': 'Budget Variance Accuracy %, EBITDA, Gross Margin %',
             'description': 'Synthesising financial data into meaningful insights, identifying trends, explaining variances and presenting financial analysis to leadership.'},
            {'code': 'FIN12', 'category': 'Behavioral', 'ev_critical': False,
             'name': 'Commercial Acuity & Cost Leadership Mindset',
             'kpi_link': 'Cost Reduction Savings, Vendor Payment Terms Optimisation',
             'description': 'Proactively identifying cost optimisation opportunities, challenging spend decisions with commercial lens and driving a cost-conscious culture.'},
            {'code': 'FIN13', 'category': 'Behavioral', 'ev_critical': False,
             'name': 'Governance, Ethics & Financial Integrity',
             'kpi_link': 'Statutory Compliance — Zero Lapses, Internal Audit Findings',
             'description': 'Upholding the highest standards of financial integrity, zero tolerance for compliance lapses, and maintaining governance culture in all financial decisions.'},
        ],
    },

    'hr': {
        'label': 'Human Resources',
        'short': 'HR',
        'icon': '👥',
        'head_title': 'CHRO / VP Human Resources',
        'comps': [
            {'code': 'HR01', 'category': 'Technical', 'ev_critical': False,
             'name': 'Talent Acquisition & Workforce Planning',
             'kpi_link': 'Critical Role Fulfilment % (≤90 days), Blue Collar Hiring vs Ramp Plan %, Cost per Hire',
             'description': 'End-to-end TA for white and blue collar roles, headcount planning aligned to production ramp, ATS management and offer-to-join conversion.'},
            {'code': 'HR02', 'category': 'Technical', 'ev_critical': False,
             'name': 'Learning & Development Programme Design',
             'kpi_link': 'Training Man-Days per Employee, Learning ROI',
             'description': 'Designing structured L&D programmes, blended learning solutions (70-20-10 model), LMS management and tracking training ROI through business outcome linkage.'},
            {'code': 'HR03', 'category': 'Technical', 'ev_critical': True,
             'name': 'Technical Academy & EV Certification Management',
             'kpi_link': 'Skill Centre Operationalisation %, Dealer Technician Certification %, After-Sales Readiness %',
             'description': 'Setting up and running the JSW Motors Skill Centre, managing EV technician certifications for plant, dealer and after-sales service technicians.'},
            {'code': 'HR04', 'category': 'Technical', 'ev_critical': False,
             'name': 'HR Business Partnering & Strategic Advisory',
             'kpi_link': 'Internal Mobility Fill Rate %, Leadership Pipeline Readiness %',
             'description': 'Partnering with function heads on people matters, translating business needs to HR solutions, managing internal mobility and talent pipeline conversations.'},
            {'code': 'HR05', 'category': 'Technical', 'ev_critical': False,
             'name': 'Compensation, Benefits & Payroll Management',
             'kpi_link': 'Payroll Accuracy %, Cost per Hire, Offer-to-Join Ratio %',
             'description': 'Compensation benchmarking, salary structuring, payroll processing accuracy, benefits design and managing total rewards competitiveness for talent attraction.'},
            {'code': 'HR06', 'category': 'Technical', 'ev_critical': False,
             'name': 'HR Analytics & Workforce Intelligence',
             'kpi_link': 'Attrition % (White Collar), Critical Talent Attrition %, Engagement Score, Diversity Hire %',
             'description': 'Building and interpreting HR MIS, attrition dashboards, engagement analytics, diversity tracking and data-driven insights for workforce decisions.'},
            {'code': 'HR07', 'category': 'Technical', 'ev_critical': False,
             'name': 'Compliance, Labour Law & POSH Management',
             'kpi_link': 'HR Compliance — Zero Major Violations, POSH Case Resolution TAT (days)',
             'description': 'Labour law compliance, PF/ESIC/gratuity management, contract labour regulations, POSH committee functioning and statutory compliance reporting.'},
            {'code': 'HR08', 'category': 'Technical', 'ev_critical': False,
             'name': 'Succession Planning & Leadership Pipeline Development',
             'kpi_link': 'Leadership Pipeline Readiness %, Critical Talent Attrition %, Internal Mobility Fill Rate %',
             'description': 'Identifying HiPo talent, building succession plans for critical roles, 9-box calibration, IDP facilitation and accelerated development programmes.'},
            {'code': 'HR09', 'category': 'Behavioral', 'ev_critical': False,
             'name': 'Culture Building, Engagement & Inclusion',
             'kpi_link': 'Employee Engagement Score %, Culture Alignment Score, Diversity Hire %',
             'description': 'Designing and driving employee engagement initiatives, building an inclusive workplace, running culture surveys and translating insights into action plans.'},
            {'code': 'HR10', 'category': 'Behavioral', 'ev_critical': False,
             'name': 'Stakeholder Management & Influencing Without Authority',
             'kpi_link': 'Critical Role Fulfilment %, Internal Mobility %, Training Man-Days',
             'description': 'Building credibility and influence with business leaders, managing multiple stakeholders simultaneously and driving people agenda without direct authority.'},
            {'code': 'HR11', 'category': 'Behavioral', 'ev_critical': False,
             'name': 'Change Management & OD During Rapid Scale-Up',
             'kpi_link': 'Culture Alignment Score, Engagement Score, Attrition %',
             'description': 'Managing people change during rapid headcount scale-up, driving cultural integration, communicating change rationale and sustaining engagement.'},
            {'code': 'HR12', 'category': 'Behavioral', 'ev_critical': False,
             'name': 'Communication, Facilitation & Coaching Skills',
             'kpi_link': 'POSH Case Resolution TAT, Engagement Score, Skill Centre Operationalisation',
             'description': 'Facilitating training sessions, coaching business leaders, communicating HR policies clearly and enabling a psychologically safe environment.'},
        ],
    },

    'procurement': {
        'label': 'Procurement & Localisation',
        'short': 'Proc',
        'icon': '🔗',
        'head_title': 'VP Procurement & Localisation',
        'comps': [
            {'code': 'PR01', 'category': 'Technical', 'ev_critical': True,
             'name': 'Localisation Strategy & Domestic Vendor Development',
             'kpi_link': 'Domestic Localisation % (BOM value), Supplier Base Development Count, Import Duty Savings (₹ Cr)',
             'description': 'Developing the India supply base for EV components, localisation roadmap execution, vendor scouting and qualifying new Tier-1 domestic suppliers.'},
            {'code': 'PR02', 'category': 'Technical', 'ev_critical': False,
             'name': 'Should-Costing & Cost Breakdown Analysis',
             'kpi_link': 'Material Cost % of Revenue, Cost Reduction vs Prior Year (₹ Cr)',
             'description': 'Building cost models: material + labour + overhead + profit for automotive components; cost driver analysis and should-cost negotiation support.'},
            {'code': 'PR03', 'category': 'Technical', 'ev_critical': False,
             'name': 'Supplier Quality Management (SQA)',
             'kpi_link': 'Supplier PPM, PPAP Clearance Rate %, Supplier Audit Score, Supplier CAPA Closure Rate %',
             'description': 'Managing supplier quality through PPAP, supplier audits, defect PPM tracking, CAPA management and supplier development for quality improvement.'},
            {'code': 'PR04', 'category': 'Technical', 'ev_critical': False,
             'name': 'Strategic Sourcing & Commercial Negotiation',
             'kpi_link': 'LTA Coverage %, Price Index Variance vs Commodity Benchmark, Cost Reduction (₹ Cr)',
             'description': 'Category strategy, RFQ management, competitive bidding, long-term agreement structuring and commodity hedging for cost stabilisation.'},
            {'code': 'PR05', 'category': 'Technical', 'ev_critical': False,
             'name': 'Vendor Qualification & PPAP Management',
             'kpi_link': 'New Vendor Qualification TAT (weeks), PPAP Clearance Rate — First Time Pass %',
             'description': 'End-to-end vendor qualification process from RFQ to approval, managing PPAP submissions, MSA, APQP documentation and first-time pass improvement.'},
            {'code': 'PR06', 'category': 'Technical', 'ev_critical': False,
             'name': 'Import-Export & Customs Regulations',
             'kpi_link': 'Import Duty Savings (₹ Cr), Domestic Localisation % (BOM value)',
             'description': 'Import duty structures, EPCG/Advance Authorisation schemes, customs classification, free trade agreement utilisation and import cost optimisation.'},
            {'code': 'PR07', 'category': 'Technical', 'ev_critical': False,
             'name': 'Supply Risk & Business Continuity Management',
             'kpi_link': 'Single-Source Dependency % of Spend, Supply Continuity — Zero Production Stoppages',
             'description': 'Supply risk assessment, identifying and reducing single-source dependencies, dual/multi-source strategy and supply continuity planning.'},
            {'code': 'PR08', 'category': 'Technical', 'ev_critical': False,
             'name': 'ESG & Responsible Procurement Practices',
             'kpi_link': 'ESG-Compliant Suppliers %',
             'description': 'Evaluating suppliers on ESG criteria (carbon, labour practices, governance), integrating ESG into supplier scorecards and building a sustainable supply base.'},
            {'code': 'PR09', 'category': 'Technical', 'ev_critical': False,
             'name': 'SAP MM / ERP Procurement Modules',
             'kpi_link': 'Supply Continuity, Supplier PPM, Cost Reduction',
             'description': 'SAP MM proficiency: purchase orders, MRP-driven procurement, GR/IR management, vendor master maintenance and ERP-based spend analytics.'},
            {'code': 'PR10', 'category': 'Technical', 'ev_critical': False,
             'name': 'Supplier CAPA & Corrective Action Management',
             'kpi_link': 'Supplier CAPA Closure Rate %, Supplier Audit Score',
             'description': 'Issuing supplier NCRs, tracking CAPA implementation, validating effectiveness of corrective actions and escalating chronic supplier quality issues.'},
            {'code': 'PR11', 'category': 'Behavioral', 'ev_critical': False,
             'name': 'Cross-Functional Collaboration (Engg/Mfg/Finance)',
             'kpi_link': 'BOM Cost vs Target %, PPAP Clearance, Supply Continuity',
             'description': 'Working effectively with Engineering on DFM, Manufacturing on PPAP and supply continuity, Finance on spend analytics and business partnering.'},
            {'code': 'PR12', 'category': 'Behavioral', 'ev_critical': False,
             'name': 'Spend Analytics & Data-Driven Procurement',
             'kpi_link': 'Price Index Variance, Material Cost %, Cost Reduction Savings',
             'description': 'Using spend data, commodity indices and supplier scorecards to drive category decisions, negotiate better and identify cost reduction opportunities.'},
            {'code': 'PR13', 'category': 'Behavioral', 'ev_critical': False,
             'name': 'Negotiation & Supplier Relationship Management',
             'kpi_link': 'LTA Coverage %, Supplier Satisfaction, Cost Reduction',
             'description': 'Building long-term strategic supplier partnerships, principled negotiation techniques and balancing commercial rigour with relationship sustainability.'},
        ],
    },

    'scm_logistics': {
        'label': 'SCM & Logistics',
        'short': 'SCM',
        'icon': '🚚',
        'head_title': 'VP SCM / Head Supply Chain',
        'comps': [
            {'code': 'SCM01', 'category': 'Technical', 'ev_critical': False,
             'name': 'Demand Planning & S&OP Facilitation',
             'kpi_link': 'Demand Forecast Accuracy %, S&OP Cycle Adherence %, Production Plan vs Actual %',
             'description': 'Statistical demand forecasting, S&OP cycle facilitation, consensus demand building across Sales/Manufacturing and managing forecast accuracy improvement.'},
            {'code': 'SCM02', 'category': 'Technical', 'ev_critical': False,
             'name': 'Production Planning & Scheduling',
             'kpi_link': 'Production Plan vs Actual Adherence %, S&OP Adherence',
             'description': 'MPS/MRP execution, daily/weekly production scheduling, capacity constraint management and production adherence tracking against approved plans.'},
            {'code': 'SCM03', 'category': 'Technical', 'ev_critical': False,
             'name': 'Inventory Optimisation & Working Capital Management',
             'kpi_link': 'FG Inventory Days (Dealer), RM Inventory Days (Plant), Inventory Accuracy %, Spare Parts Inventory (₹ Cr)',
             'description': 'Safety stock modelling, inventory norms setting, ABC/XYZ analysis, perpetual counting and managing inventory levels to target working capital days.'},
            {'code': 'SCM04', 'category': 'Technical', 'ev_critical': False,
             'name': 'Logistics & Transport Management (OTIF)',
             'kpi_link': 'Vehicle Dispatch OTIF %, Outbound Freight Cost per Unit (₹), Transit Damage Rate, Dealer Delivery Lead Time (days)',
             'description': 'Outbound logistics management, carrier selection, route optimisation, OTIF tracking, transit damage reduction and freight cost management.'},
            {'code': 'SCM05', 'category': 'Technical', 'ev_critical': False,
             'name': 'Warehouse Management Systems & Operations',
             'kpi_link': 'Inventory Accuracy %, Warehouse Space Utilisation %',
             'description': 'WMS implementation and operations, cycle counting, space utilisation, material handling systems, inbound and outbound warehouse process management.'},
            {'code': 'SCM06', 'category': 'Technical', 'ev_critical': False,
             'name': 'Spare Parts Planning & After-Market Supply Chain',
             'kpi_link': 'Spare Parts Availability % (First Fill Rate), Back-order Rate %, Spare Parts Inventory (₹ Cr)',
             'description': 'Spare parts demand forecasting, first fill rate management, regional warehouse network design and managing back-order resolution for after-sales.'},
            {'code': 'SCM07', 'category': 'Technical', 'ev_critical': False,
             'name': 'Supply Chain Analytics & Digital SCM Tools',
             'kpi_link': 'ERP / SCM System Uptime %, Demand Forecast Accuracy',
             'description': 'Proficiency in ERP SCM modules (SAP/Oracle), supply chain analytics dashboards, OTIF tracking systems and digital supply chain visibility tools.'},
            {'code': 'SCM08', 'category': 'Technical', 'ev_critical': False,
             'name': 'Sustainable Logistics & Carbon Footprint Management',
             'kpi_link': 'Carbon Footprint — Outbound Logistics (kgCO₂/unit)',
             'description': 'Measuring and reducing logistics carbon footprint, green carrier selection, consolidated shipment planning and ESG reporting for outbound logistics.'},
            {'code': 'SCM09', 'category': 'Behavioral', 'ev_critical': False,
             'name': 'Cross-Functional S&OP Coordination',
             'kpi_link': 'S&OP Cycle Adherence %, Production Plan Adherence, OTIF %',
             'description': 'Facilitating cross-functional alignment between Sales, Manufacturing, Finance and Procurement in the monthly S&OP cycle for cohesive supply-demand balancing.'},
            {'code': 'SCM10', 'category': 'Behavioral', 'ev_critical': False,
             'name': 'Supply Disruption Problem Solving & CAPA',
             'kpi_link': 'Supply Continuity, OTIF %, Spare Parts Availability %',
             'description': 'Rapid identification and resolution of supply disruptions, root cause analysis on supply failures and implementing sustainable corrective actions.'},
            {'code': 'SCM11', 'category': 'Behavioral', 'ev_critical': False,
             'name': 'Stakeholder Communication & Escalation Management',
             'kpi_link': 'Dealer Delivery Lead Time, OTIF %, Spare Parts Availability',
             'description': 'Proactive communication on supply risks and delivery timelines with dealers, Sales and Manufacturing; structured escalation when OTIF risks arise.'},
        ],
    },

    'it_digital': {
        'label': 'IT & Digital',
        'short': 'IT',
        'icon': '💻',
        'head_title': 'CIO / VP IT & Digital',
        'comps': [
            {'code': 'IT01', 'category': 'Technical', 'ev_critical': False,
             'name': 'Enterprise Systems (ERP/MES/HRMS) Management',
             'kpi_link': 'Core Systems Uptime %, ERP Go-Live on Schedule (Milestone)',
             'description': 'SAP/Oracle ERP implementation and governance, MES integration for production, HRMS management and ensuring 99%+ uptime of business-critical applications.'},
            {'code': 'IT02', 'category': 'Technical', 'ev_critical': True,
             'name': 'MES & Plant Digital Integration',
             'kpi_link': 'MES Integration — Plant Coverage %, ERP Go-Live Milestone',
             'description': 'Manufacturing Execution System rollout, connecting production lines to MES, real-time production data management and plant-floor digital integration.'},
            {'code': 'IT03', 'category': 'Technical', 'ev_critical': True,
             'name': 'Connected Vehicle & OTA Platform Architecture',
             'kpi_link': 'Connected Vehicle Platform Readiness %, EV Software OTA Capability',
             'description': 'Telematics platform design, OTA update infrastructure, vehicle connectivity architecture, data ingestion from connected fleet and customer app integration.'},
            {'code': 'IT04', 'category': 'Technical', 'ev_critical': False,
             'name': 'Cybersecurity & Data Privacy (DPDP/ISO 27001)',
             'kpi_link': 'Cybersecurity Incidents (P1/P2) — Zero, DPDP / Data Privacy Compliance %',
             'description': 'Information security management, DPDP Act compliance, ISO 27001 controls, threat detection, incident response and OEM data protection requirements.'},
            {'code': 'IT05', 'category': 'Technical', 'ev_critical': False,
             'name': 'Data Analytics, BI & Self-Service Reporting',
             'kpi_link': 'Data Platform / Analytics Adoption %, ERP Go-Live Milestone',
             'description': 'Data platform architecture, BI tool deployment (Power BI/Tableau), building self-service dashboards across functions and managing data governance.'},
            {'code': 'IT06', 'category': 'Technical', 'ev_critical': False,
             'name': 'Dealer Management Systems (DMS) & Digital Retail',
             'kpi_link': 'DMS Adoption % (Dealers), Customer App / Portal Uptime %, Digital Lead Processing TAT',
             'description': 'DMS rollout and support across dealer network, customer-facing digital touchpoints management, app uptime monitoring and digital retail enablement.'},
            {'code': 'IT07', 'category': 'Technical', 'ev_critical': False,
             'name': 'IT Service Management (ITSM) & SLA Governance',
             'kpi_link': 'IT Service Desk — SLA Compliance %, Core Systems Uptime %',
             'description': 'ITSM process implementation (ITIL), service desk operations, SLA definition and monitoring, incident/problem/change management framework.'},
            {'code': 'IT08', 'category': 'Technical', 'ev_critical': False,
             'name': 'IT CAPEX Management & Technology Vendor Governance',
             'kpi_link': 'IT CAPEX vs Budget %, Software Licence Compliance %',
             'description': 'IT budget planning and tracking, technology procurement, vendor contract management, software asset management and licence compliance.'},
            {'code': 'IT09', 'category': 'Technical', 'ev_critical': False,
             'name': 'Business Continuity & Disaster Recovery Management',
             'kpi_link': 'Business Continuity — RTO Adherence %, Core Systems Uptime %',
             'description': 'BCP/DRP planning, recovery time objective (RTO) setting and testing, DR drill execution, failover testing and business continuity documentation.'},
            {'code': 'IT10', 'category': 'Behavioral', 'ev_critical': False,
             'name': 'Cross-Functional Digital Transformation Leadership',
             'kpi_link': 'Data Platform Adoption %, ERP Go-Live Milestone, MES Coverage %',
             'description': 'Leading IT-business alignment for digital transformation, driving adoption across functions, managing change resistance and building digital capability.'},
            {'code': 'IT11', 'category': 'Behavioral', 'ev_critical': False,
             'name': 'Analytical Problem Solving & IT Risk Management',
             'kpi_link': 'IT Audit Findings — Critical Open, Cybersecurity Incidents, RTO Adherence',
             'description': 'Identifying and mitigating IT risks, root cause analysis for system incidents, managing audit observations and ensuring zero critical open findings.'},
            {'code': 'IT12', 'category': 'Behavioral', 'ev_critical': False,
             'name': 'Stakeholder Communication & Change Management',
             'kpi_link': 'ERP Go-Live Milestone, DMS Adoption %, Data Platform Adoption %',
             'description': 'Communicating technology changes to business stakeholders, managing ERP/MES go-live change management and building user adoption through training.'},
        ],
    },

    'manufacturing': {
        'label': 'Manufacturing',
        'short': 'Mfg',
        'icon': '🏭',
        'head_title': 'COO / VP Manufacturing',
        'comps': [
            {'code': 'MF01', 'category': 'Technical', 'ev_critical': True,
             'name': 'EV Plant Setup & Production Ramp Management',
             'kpi_link': 'Plant Readiness Index %, Production Line Qualification (PPAP Sign-Off) %, CAPEX Commissioning On-Schedule %',
             'description': 'Greenfield EV plant readiness management, trial run planning, PPAP sign-off coordination and managing ramp-up from commissioning to full production.'},
            {'code': 'MF02', 'category': 'Technical', 'ev_critical': True,
             'name': 'High Voltage (HV) Safety & EV Manufacturing Safety',
             'kpi_link': 'LTIFR (LTIs per million man-hours), Near-Miss Reporting Rate, Environmental Non-Conformances',
             'description': 'HV system awareness, LOTO for EV lines, PPE for high-voltage environments, Li-ion battery handling safety and safety leadership in the EV plant.'},
            {'code': 'MF03', 'category': 'Technical', 'ev_critical': False,
             'name': 'OEE Improvement & TPM Implementation',
             'kpi_link': 'Overall Equipment Effectiveness (OEE) %, Installed Capacity Utilisation %',
             'description': '8-pillar TPM, autonomous and planned maintenance, OEE measurement (Availability × Performance × Quality), loss analysis and OEE improvement programmes.'},
            {'code': 'MF04', 'category': 'Technical', 'ev_critical': True,
             'name': 'EV Assembly Process & Line Operations',
             'kpi_link': 'Volume Production vs Plan %, Throughput Time (hrs/vehicle), Capacity Utilisation %',
             'description': 'EV assembly sequence, line balancing, takt time management, station layouts, material flow in greenfield EV plant and daily production management.'},
            {'code': 'MF05', 'category': 'Technical', 'ev_critical': False,
             'name': 'Quality Systems (IATF 16949) & Defect Reduction',
             'kpi_link': 'Defects per Unit (DPU), First Time Through (FTT) %, Warranty PPM (Plant Attributable)',
             'description': 'IATF 16949 quality management, in-station quality controls, DPU and FTT measurement, non-conformance management and warranty PPM reduction.'},
            {'code': 'MF06', 'category': 'Technical', 'ev_critical': False,
             'name': 'Lean Manufacturing & Waste Elimination',
             'kpi_link': 'Scrap & Rework Cost (₹ Cr), Throughput Time (hrs/vehicle), OEE %',
             'description': '7 wastes elimination, value stream mapping, Kaizen facilitation, standardised work, scrap and rework cost reduction through systematic lean tools.'},
            {'code': 'MF07', 'category': 'Technical', 'ev_critical': False,
             'name': 'Manufacturing Cost Control & Energy Management',
             'kpi_link': 'Manufacturing Cost per Unit (₹ Lakh), Energy Cost per Unit (₹), Scrap & Rework Cost',
             'description': 'Manufacturing cost structure, variable vs fixed cost management, energy monitoring and reduction programmes, and driving cost per unit to target.'},
            {'code': 'MF08', 'category': 'Technical', 'ev_critical': False,
             'name': 'Environmental Compliance & EHS Management',
             'kpi_link': 'Environmental Non-Conformances (Zero), Water Intensity (kL/vehicle), LTIFR',
             'description': 'ISO 14001 / ISO 45001 compliance, environmental monitoring, statutory environmental reporting, EHS management system implementation.'},
            {'code': 'MF09', 'category': 'Technical', 'ev_critical': False,
             'name': '5S, Visual Management & Shop Floor Discipline',
             'kpi_link': 'FTT %, DPU, LTIFR',
             'description': 'Implementing and sustaining 5S on the shop floor, visual controls, shadow boards, standard work adherence and building a culture of shop floor discipline.'},
            {'code': 'MF10', 'category': 'Technical', 'ev_critical': False,
             'name': 'MES / ERP & Digital Manufacturing Tools',
             'kpi_link': 'Production Plan vs Actual %, OEE %, Throughput Time',
             'description': 'Manufacturing Execution System usage for production data capture, downtime logging, quality recording, shift handover and ERP integration for production orders.'},
            {'code': 'MF11', 'category': 'Technical', 'ev_critical': False,
             'name': 'Root Cause Analysis & Structured Problem Solving',
             'kpi_link': 'DPU, Customer Complaints — Plant Origin, Warranty PPM',
             'description': '8D, 5-Why, A3, fishbone analysis for manufacturing defects, warranty escapes and quality incidents; implementing verified countermeasures.'},
            {'code': 'MF12', 'category': 'Behavioral', 'ev_critical': False,
             'name': 'Safety-First Mindset & Near-Miss Reporting Culture',
             'kpi_link': 'Near-Miss Reporting Rate (per 100 employees), LTIFR',
             'description': 'Proactively identifying hazards, reporting near-misses without fear, speaking up on safety concerns and leading by example on safety behaviour.'},
            {'code': 'MF13', 'category': 'Behavioral', 'ev_critical': False,
             'name': 'Cross-Functional Collaboration (Engg/Quality/SCM)',
             'kpi_link': 'FTT %, Production Plan Adherence, Warranty PPM',
             'description': 'Working with Engineering on PPAP and manufacturing sign-off, with Quality on defect resolution, and with SCM on material availability for production targets.'},
            {'code': 'MF14', 'category': 'Behavioral', 'ev_critical': False,
             'name': 'Continuous Improvement (Kaizen) Mindset',
             'kpi_link': 'OEE %, Scrap & Rework Cost, DPU, Energy Cost per Unit',
             'description': 'Proactively identifying improvement opportunities, initiating and sustaining Kaizen activities, daily CI circle participation and connecting improvement to KPIs.'},
            {'code': 'MF15', 'category': 'Behavioral', 'ev_critical': False,
             'name': 'Team Leadership & Shift Performance Management',
             'kpi_link': 'Volume Production vs Plan %, LTIFR, Near-Miss Reporting Rate',
             'description': 'Leading production teams on shift, setting clear expectations, providing structured feedback, managing shift handover communication and building team accountability.'},
        ],
    },
}

ROLE_CHOICES = [
    ('FH', 'Functional Head / Manager / GM'),
    ('GET', 'Graduate Engineer Trainee (GET)'),
    ('MT', 'Management Trainee (MT)'),
]

FUNCTION_CHOICES = [(k, v['label']) for k, v in FUNCTIONS.items()]
